package oopnet.chess.client;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;
import java.util.Random;

/**
 * Class for client properties.
 * <br>
 * Example usage:
 * <pre>
 *     ClientProperties properties = new ClientProperties();
 *     String address = properties.getProperty(ClientProperties.SERVER_ADDRESS_KEY);
 *     properties.setProperty(ClientProperties.NICKNAME_KEY, "new_nickname");
 *     properties.save();
 * </pre>
 */
public class ClientProperties extends Properties {


    public static final String SERVER_ADDRESS_KEY = "server.address";
    public static final String NICKNAME_KEY = "nickname";
    public static final String SERVER_PORT_KEY = "server.port";
    public static final String TOKEN_KEY = "token";

    private static final File PROPERTIES_FILE = new File(defaultDirectory(), "oopchess" + File.separator + "client.properties");


    {
        // Load values
        if (PROPERTIES_FILE.exists()) {
            try {
                this.load(new FileReader(PROPERTIES_FILE));
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            // Or set the default values
            setProperty(NICKNAME_KEY, "Player" + new Random().nextInt(1000));
            setProperty(SERVER_ADDRESS_KEY, "localhost");
            setProperty(SERVER_PORT_KEY, "8080");
            save();
        }
    }


    // Find the default directory to save the files
    // https://stackoverflow.com/a/16660314/10728047
    private static String defaultDirectory() {
        String name = System.getProperty("os.name").toUpperCase();
        if (name.contains("WIN")) {
            return System.getenv("AppData");
        }
        return System.getProperty("user.home") + "/Library/Application Support";
    }

    public void save() {
        try {
            PROPERTIES_FILE.getParentFile().mkdirs();
            PROPERTIES_FILE.createNewFile();
            this.store(new FileOutputStream(PROPERTIES_FILE), "Do not edit this file");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
